In [46]:

'''

GUILHERME LIMA DE SOUSA - 
ESTUDO DE CASO: TONELADAS TRANSPORTADAS EM FERROVIAS BRASILEIRAS
OBJETIVO: PREDIÇÃO USANDO RANDOMFORESTREGRESSOR

ENTRE EM CONTATO COMIGO NO LINKEDIN: 
www.linkedin.com/in/guilherme-lima-747355169

'''


import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import random
import mlflow
import openpyxl


################################################################################


# ETL DA BASE

################################################################################



##CONFIGURANDO NUMEROS COM 2 CASAS DECIMAIS
pd.set_option('Float_format','{:.2f}'.format)



##  CARREGANDO INFORMAÇÕES DA FORÇA DE TRABALHO NAS FERROVIAS
caminho_cnt_empregados = 'C:/Users/Guilh/OneDrive/Área de Trabalho/1-MATERIAIS DE ESTUDO/01 - DIVERSOS/01-SCIKIT_LEARN/01-INPUT/CNT/QTD_TRABALHADORES_FERROVIAS_CNT.xlsx'
base_empregados_cnt = pd.read_excel(caminho_cnt_empregados, engine='openpyxl')
empregados_cnt = base_empregados_cnt.melt(id_vars=['CONCESSIONARIA'], var_name='ANO', value_name='Qtd_empregados')
empregados_cnt = empregados_cnt.rename(columns={'CONCESSIONARIA':'Ferrovia'})
print(empregados_cnt.head(1))
print('----------------')

# CARREGANDO INFORMAÇÕES DOS INVESTIMENTOS NAS FERROVIAS
caminho_cnt_investimentos = 'C:/Users/Guilh/OneDrive/Área de Trabalho/1-MATERIAIS DE ESTUDO/01 - DIVERSOS/01-SCIKIT_LEARN/01-INPUT/CNT/INVESTIMENTOS_FERROVIAS_CNT.xlsx'
base_investimentos_cnt = pd.read_excel(caminho_cnt_investimentos, engine='openpyxl')
investimentos_cnt = base_investimentos_cnt.melt(id_vars=['CONCESSIONARIA'], var_name='ANO', value_name='Investimentos_malha')
investimentos_cnt = investimentos_cnt.rename(columns={'CONCESSIONARIA':'Ferrovia'})
print(investimentos_cnt.head(1))
print('----------------')

# CARREGANDO INFORMAÇÕES ANTT FERROVIAS
caminho_antt = 'C:/Users/Guilh/OneDrive/Área de Trabalho/1-MATERIAIS DE ESTUDO/01 - DIVERSOS/01-SCIKIT_LEARN/01-INPUT/ANTT'
arquivos = glob.glob(os.path.join(caminho_antt,'*.csv'))
base_antt = pd.concat([pd.read_csv(i, sep=';', encoding='latin1') for i in arquivos], ignore_index = True)

## REMOVENDO PONTO DA COLUNA
base_antt['TU'] = base_antt['TU'].str.replace('.','',regex=False)
base_antt['TKU'] = base_antt['TKU'].str.replace('.','',regex=False)

## ALTERANDO FORMATAÇÃO DA COLUNA
base_antt['TKU'] = base_antt['TKU'].fillna(0)
base_antt['TKU'] = base_antt['TKU'].astype(float)
base_antt['TU'] = base_antt['TU'].astype(int)
base_antt['TKU'] = base_antt['TKU'].astype(int)
base_antt['Mes_Ano'] = pd.to_datetime(base_antt['Mes_Ano'], format='%m/%Y')

## CRIANDO COLUNAS
base_antt['MÊS'] = base_antt['Mes_Ano'].dt.month
base_antt['ANO'] = base_antt['Mes_Ano'].dt.year

#REMOVENDO DUPLICADOS E NULOS
base_antt = base_antt.drop_duplicates()

# REMOVENDO COLUNA TKU POIS O OBJETIVO É APNAS TU
base_antt = base_antt.drop('TKU', axis=1)
base_antt = base_antt.drop('Mes_Ano', axis=1)

# REMOVENDO VALORES ABAIXO DE 1 TONELADA
base_antt = base_antt[base_antt["TU"]>= 1000]
print(base_antt.head(1))


base_juncao_um = pd.merge(base_antt, empregados_cnt, on=['ANO', 'Ferrovia'])
base_completa = pd.merge(base_juncao_um, investimentos_cnt, on=['ANO', 'Ferrovia'])
base_completa['Investimentos_malha'] = base_completa['Investimentos_malha'].map('{:.2f}'.format).astype(float)
base_completa.head(1)


# REMOVENDO VALORES ABAIXO DE 1 TONELADA
base_original = base_completa[base_completa["TU"]>= 1000]

# VENDO A BASE
base_original.head(-5)

  Ferrovia   ANO  Qtd_empregados
0      EFC  2006            3608
----------------
  Ferrovia   ANO  Investimentos_malha
0      EFC  2006               578.10
----------------
  Ferrovia       Mercadoria_ANTT                 Estacao_Origem UF_Origem  \
1      EFC  Bebidas e Vasilhames  Ponta da Madeira Pêra do Píer        MA

  Estacao_Destino UF_Destino    TU  MÊS   ANO
1      Imperatriz         MA  1636    1  2006

,Ferrovia,Mercadoria_ANTT,Estacao_Origem,UF_Origem,Estacao_Destino,UF_Destino,TU,MÊS,ANO,Qtd_empregados,Investimentos_malha
0,EFC,Bebidas e Vasilhames,Ponta da Madeira Pêra do Píer,MA,Imperatriz,MA,1636,1,2006,3608,578.10
1,EFC,Cobre,Paraupebas,PA,Ponta da Madeira Cobre,MA,24461,1,2006,3608,578.10
2,EFC,Ferro Gusa,Açailândia,MA,Ponta da Madeira Pêra do Píer,MA,116272,1,2006,3608,578.10
3,EFC,Ferro Gusa,Marabá,PA,Ponta da Madeira Pêra do Píer,MA,205242,1,2006,3608,578.10
4,EFC,Ferro Gusa,Santa Inês,MA,Ponta da Madeira Pêra do Píer,MA,8000,1,2006,3608,578.10
...,...,...,...,...,...,...,...,...,...,...,...
103292,RMS,Soja,Londrina,PR,D Pedro II,PR,9106,12,2021,5347,343.60
103293,RMS,Soja,Marialva,PR,D Pedro II,PR,19781,12,2021,5347,343.60
103294,RMS,Soja,Maringa,PR,D Pedro II,PR,118597,12,2021,5347,343.60
103295,RMS,Soja,Maringa,PR,São Francisco do Sul,SC,136488,12,2021,5347,343.60
103296,RMS,Soja,Rolandia,PR,D Pedro II,PR,8623,12,2021,5347,343.60

In [48]:


####################################################################################

#     CRIANDO DATASET DO MODELO

####################################################################################

'''

AQUI VAMOS CRIAR O DATASET DO MODELO
FAZENDO ETL COM AS COLUNAS CATEGORICAS E APLICANDO CÓDIGOS PARA CADA UMA, 
POSTERIORMENTE USANDO AS COLUNAS NUMERICAS REPRESENTADAS COMO VARIAVEIS DO MODELO.
EM VEZ DE USAR O NOME DA FERROVIA ESTAMOS CRIANDO UM CÓDIGO DISTINTO DELA.

'''


# REPRODUTIBILIDADE
np.random.seed(2)


## BASE MODELO
#print(base_original.columns)
print('--------------------')
base_modelo = base_original

# TRANSFORMANDO COLUNAS
base_modelo['ANO'] = base_modelo['ANO'].astype(int)
base_modelo['MÊS'] = base_modelo['MÊS'].astype(int)
base_modelo['TU'] = base_modelo['TU'].astype(int)

#
############### CRIANDO OS CÓDIGOS DE CADA CATEGORIA
# SELECIONA APENAS AS COLUNAS STRING/CATEGORIAS/OBJETO
categ = base_modelo.select_dtypes(include=['object', 'category']).copy()
# LAMBDA QUE TRANSFORMA AS COLUNAS E NUMEROS
cod_categorica_hoje_1 = categ.apply(lambda col: col.astype('category').cat.codes)
# RENOMEANDO AS COLUNAS DE CODIGO COM PREFIXO
cod_categorica_1 = cod_categorica_hoje_1.add_prefix('Codigo_')


# CONCATENANDO AS BASES DE CODIGOS COM A ORIGINAL
codigos_categorias = pd.concat([base_modelo, cod_categorica_1], axis=1)

print('################# BASE COM DE:PARA ########################\n')
# BASE COM TUDO



##########  PARA VISUALIZAR DE:PARA DE COLUNA ESPECIFICA
#visualizar_de_para = codigos_categorias[['Ferrovia', 'Codigo_Ferrovia']].drop_duplicates().reset_index(drop=True)
#print('\n################# VERIFICAR ########################\n')
#print(visualizar_de_para.head(3))


########## ENGENHARIA DE ATRIBUTOS - FEATURE ENGINEERING - CLUSTER KMEANS
grupos_produtos = pd.read_csv('C:/Users/Guilh/OneDrive/Área de Trabalho/1-MATERIAIS DE ESTUDO/01 - DIVERSOS/01-SCIKIT_LEARN/03-KMEANS/01-ANTT_FERROVIAS/BASE_ANTT_COM_KMEANS.csv', sep=';')
grupos_produtos = grupos_produtos.drop_duplicates()

chaves = ['MÊS', 'ANO', 'Ferrovia', 'Mercadoria_ANTT', 'Estacao_Origem', 'UF_Origem', 'Estacao_Destino', 'UF_Destino']

mesclando_df = codigos_categorias.merge( grupos_produtos[chaves + ['cluster_produto']], on=chaves, how="left")
mesclando_df = mesclando_df[['MÊS', 'ANO', 'Ferrovia', 'Codigo_Ferrovia', 'Mercadoria_ANTT', 'Codigo_Mercadoria_ANTT', 'Codigo_Estacao_Origem', 'Estacao_Origem',
                             'UF_Origem', 'Codigo_UF_Origem', 'Estacao_Destino', 'Codigo_Estacao_Destino', 'UF_Destino', 'Codigo_UF_Destino',
                             'TU', 'Qtd_empregados', 'Investimentos_malha', 'cluster_produto']]


codigos_categorias = mesclando_df
codigos_categorias = codigos_categorias.dropna()
codigos_categorias['cluster_produto'] = codigos_categorias['cluster_produto'].astype(int)
codigos_categorias.head(5)

--------------------
################# BASE COM DE:PARA ########################

,MÊS,ANO,Ferrovia,Codigo_Ferrovia,Mercadoria_ANTT,Codigo_Mercadoria_ANTT,Codigo_Estacao_Origem,Estacao_Origem,UF_Origem,Codigo_UF_Origem,Estacao_Destino,Codigo_Estacao_Destino,UF_Destino,Codigo_UF_Destino,TU,Qtd_empregados,Investimentos_malha,cluster_produto
0,1,2006,EFC,0,Bebidas e Vasilhames,10,268,Ponta da Madeira Pêra do Píer,MA,5,Imperatriz,153,MA,5,1636,3608,578.10,1
1,1,2006,EFC,0,Cobre,21,246,Paraupebas,PA,9,Ponta da Madeira Cobre,235,MA,5,24461,3608,578.10,0
2,1,2006,EFC,0,Ferro Gusa,40,32,Açailândia,MA,5,Ponta da Madeira Pêra do Píer,236,MA,5,116272,3608,578.10,0
3,1,2006,EFC,0,Ferro Gusa,40,215,Marabá,PA,9,Ponta da Madeira Pêra do Píer,236,MA,5,205242,3608,578.10,0
4,1,2006,EFC,0,Ferro Gusa,40,308,Santa Inês,MA,5,Ponta da Madeira Pêra do Píer,236,MA,5,8000,3608,578.10,0

In [49]:
####################################################################################

#     TRANSFORMANDO DATASET DO MODELO RANDOMFOREST

####################################################################################

''' 
AQUI ESTOU REMOVENDO OS VALORES MENORES DE 1000 MIL TONELADAS DE MOVIMENTAÇÃO
POIS ABAIXO DE MIL DEIXA O MODELO RUIM, MUITO COMPLEXO PRA ENTENDER OS DADOS
QUE VARIAM DE ZERO A MILHOES.

'''
# CRIANDO A BASE
base_treino = codigos_categorias.select_dtypes(exclude=['object', 'category']).copy()
base_treino['cluster_produto'] = base_treino['cluster_produto'].astype(int)


# SALVANDO BASE DO MODELO COMPLETA SEM FILTROS
base_modelo_completa = base_treino

# LIMITANDO A BASE REMOVENDO 2023
base_treino = base_treino[base_treino['ANO'] != 2023][list(base_treino.columns)]


# REMOVENDO OS OUTLIERS - TUDO QUE É MENOR DE MIL TONELADAS
base_treino = base_treino[base_treino['TU'] >= 1000.00]
base_modelo = base_treino



#REMOVENDO DUPLICADOS
base_treino = base_treino.drop_duplicates()


# REMOVENDO OS OUTLIERS - TUDO QUE ESTÁ MAIOR DO 3º QUARTIL EM TONELADAS
#q3 = base_treino['TU'].quantile(0.75)
#base_treino = base_treino[base_treino['TU'] <= q3]
#base_modelo = base_treino



# LOGARITMO BASE10
base_modelo['TU_LOG10'] = np.log10(base_modelo['TU'])


# REMOVENDO COLUNA REAL
base_modelo = base_modelo.drop('TU', axis=1)


base_modelo = base_modelo[["MÊS", "ANO", "Codigo_Ferrovia", "Codigo_Mercadoria_ANTT",
                          "Codigo_Estacao_Origem", "Codigo_UF_Origem", "Codigo_Estacao_Destino",
                          "Codigo_UF_Destino", "cluster_produto", "TU_LOG10", 'Qtd_empregados', 'Investimentos_malha']]


print('################# BASE MODELO ########################')
print(base_modelo.head(3))
base_modelo.describe()

################# BASE MODELO ########################
   MÊS   ANO  Codigo_Ferrovia  Codigo_Mercadoria_ANTT  Codigo_Estacao_Origem  \
0    1  2006                0                      10                    268
1    1  2006                0                      21                    246
2    1  2006                0                      40                     32

   Codigo_UF_Origem  Codigo_Estacao_Destino  Codigo_UF_Destino  \
0                 5                     153                  5
1                 9                     235                  5
2                 5                     236                  5

   cluster_produto  TU_LOG10  Qtd_empregados  Investimentos_malha
0                1      3.21            3608               578.10
1                0      4.39            3608               578.10
2                0      5.07            3608               578.10

,MÊS,ANO,Codigo_Ferrovia,Codigo_Mercadoria_ANTT,Codigo_Estacao_Origem,Codigo_UF_Origem,Codigo_Estacao_Destino,Codigo_UF_Destino,cluster_produto,TU_LOG10,Qtd_empregados,Investimentos_malha
count,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00,103302.00
mean,6.56,2012.97,6.91,49.43,199.28,9.78,178.98,11.75,0.50,4.03,5822.27,418.21
std,3.43,4.69,3.94,27.81,107.68,4.91,96.10,5.59,1.01,0.68,2478.03,374.86
min,1.00,2006.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,130.00,0.00
25%,4.00,2009.00,3.00,22.00,111.00,6.00,100.00,6.00,0.00,3.51,4429.00,185.44
50%,7.00,2013.00,7.00,53.00,210.00,9.00,188.00,13.00,0.00,3.92,5651.00,339.58
75%,10.00,2017.00,12.00,75.00,288.00,14.00,271.00,18.00,0.00,4.41,7565.00,518.93
max,12.00,2021.00,12.00,93.00,374.00,18.00,330.00,19.00,3.00,7.14,10272.00,4447.71

In [51]:

'''

HIPÓTESE NULA = SERÁ QUE MEU MODELO CONSEGUE EXPLICAR AS TONELADAS TRANSPORTADAS
APENAS COM AS DEMAIS COLUNAS DO NOSSO DATASET ?


############# PARAMETROS DO MODELO
MODELO COM VALIDAÇÃO CRUZADA DE 5 FOLDS CRIADO COM OS PARAMETROS:

N_ESTIMATORS = 300
300 ARVORES DE DECISÃO NO MÁXIMO

MAXDEPTH = 15
PERMITE CRIAR ARVORES MAIS PROFUNDAS E TRAZ ALEATORIEDADE AOS DADOS, GENERALIZAÇÃO.

RANDOM_STATE = 2
REPLICABILIDADE DE RESULTADOS

MAX_FEATURES = 'SQRT' 
ELE NÃO USA TODAS AS FEATURES NOS NÓS, ELE USA A RAIZ QUADRADA DO TOTAL DE COLUNAS.
DESTA FORMA O MODELO É FORÇADO COM DADOS E CENÁRIOS COMPLEXOS.

MIN_SAMPLES_SPLIT = 10
O MODELO SÓ VAI CRIAR OUTRO NÓ SE TIVER PELO MENOS 10 REGISTROS PRA SEGUIR ADIANTE

MIN_SAMPLES_LEAF = 5
CADA FOLHA FINAL DEVE CONTER PELO MENOS 5 REGISTROS


############# AVALIAÇÕES
# MAE (ERRO ABSOLUTO MEDIO)
Em média, o modelo erra cerca de 38.327 toneladas na previsão de TU. Esse valor deve ser 
interpretado em relação à escala dos dados — se TU varia de 0 a milhões, esse erro pode ser tolerável; se não, 
pode ser alto ......Em nossa base a coluna TARGET varia entre 0 e 13.858.719 então 38.327 é tolerável

# MSE (MEAN SQUARED ERROR) - Média dos erros ao quadrado. 
Penaliza fortemente grandes erros e destaca discrepâncias mais severas.

# MAPE
Este é o erro médio (MAE) só que em percentual.

# RMSE
Raiz do erro quadratico médio - (Raise mean squared error)
Esse erro penaliza mais fortemente grandes erros. Um RMSE muito maior que o MAE (como no nosso cenario 274.067) indica que 
há outliers ou erros muito grandes em alguns casos que estão influenciando bastante a performance.

# MEDAE
Este é a mediana dos erros, mostra como os erros estão distribuidos, o meio entre eles.

Avaliamos:
MAE para entender o erro médio bruto.
MAPE é o MAE em %.
RMSE se quiser punir grandes erros, fica sempre maior mas não tanto.
MedAE onde é o meio ? mediana dos erros.

'''


############################################################################


#  MODELO PRINCIPAL

############################################################################

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import KFold, cross_val_score, train_test_split, learning_curve, TimeSeriesSplit
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score, f1_score, classification_report
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_absolute_percentage_error, median_absolute_error
from sklearn.datasets import make_regression
from sklearn.dummy import DummyRegressor


## DEFININDO MLFLOW
mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment(experiment_id=540394382883761644)


# REPRODUTIBILIDADE
np.random.seed(2)

base_modelo = base_modelo.sort_values(by=["ANO", "MÊS"])
########################  CRIANDO MODELO PRINCIPAL
# DEFININDO X (VAR DEPENDENTE) Y (VAR TARGET)
x = base_modelo.drop(columns=['TU_LOG10'])
y = base_modelo['TU_LOG10']


# ORDENAÇÃO DOS DADOS PARA A BASE DE TREINO
x = x[['MÊS', 'ANO', 'Codigo_Ferrovia', 'Codigo_Mercadoria_ANTT', 'Codigo_Estacao_Origem',
                                           'Codigo_UF_Origem', 'Codigo_Estacao_Destino', 'Codigo_UF_Destino', 'cluster_produto', 'Qtd_empregados', 'Investimentos_malha']]


# SEPARANDO TREINO E TESTE
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)



with mlflow.start_run():
    mlflow.sklearn.autolog()
    # CRIANDO MODELO
    modelo = RandomForestRegressor(n_estimators=152, 
                               max_depth=20, 
                               random_state=2, 
                               max_features=0.8, 
                               min_samples_split=17, 
                               min_samples_leaf=3,
                               bootstrap=False)

    # VALIDAÇÃO CRUZADA
    kf = KFold(n_splits=5, shuffle= True, random_state=2)
    cross_validation = cross_val_score(modelo, x, y, cv=kf, scoring='r2')

    # APLICANDO LOG() PARA MELHORAR A DISTRIBUIÇÃO DO MODELO - evita heterocedasticidade
    #y_train_log = np.log1p(y_train)


    # TREINANDO O MODELO
    modelo.fit(x_train, y_train, sample_weight=(1 / (np.abs(base_modelo.loc[x_train.index, 'TU_LOG10'] - base_modelo.loc[x_train.index, 'TU_LOG10'].median()) + 1)))


    # USANDO MODELO NO COJUNTO DE TESTE - PREDIÇÃO
    y_pred = modelo.predict(x_test)


    # OBTENDO R2 DA PREDIÇÃO ANTERIOR
    ACC_MODELO = r2_score(y_test, y_pred)

    # ERRO PERCENTUAL MÉDIO COM LOG10
    MAE_LOG10 = mean_absolute_error(y_test, y_pred)
    MSE_LOG10 = mean_squared_error(y_test, y_pred)
    RMSE_LOG10 = np.sqrt(mean_squared_error(y_test, y_pred))
    MAPE_LOG10 = mean_absolute_percentage_error(y_test, y_pred)
    MEDAE_LOG10 = median_absolute_error(y_test, y_pred)


    # ERRO PERCENTUAL MÉDIO SEM LOG10
    MAE_REAL = mean_absolute_error(10**y_test, 10**y_pred)
    MSE_REAL = mean_squared_error(10**y_test, 10**y_pred)
    RMSE_REAL = np.sqrt(mean_squared_error(10**y_test, 10**y_pred))
    MAPE_REAL = mean_absolute_percentage_error(10**y_test, 10**y_pred)
    MEDAE_REAL = median_absolute_error(10**y_test, 10**y_pred)


    ##########  DEFININDO AS METRICAS QUE VAO PARA O MLFLOW
    metricas_mlflow = {
    "MAE_LOG10": MAE_LOG10,
    "MSE_LOG10": MSE_LOG10,
    "RMSE_LOG10": RMSE_LOG10,
    "MAPE_LOG10": MAPE_LOG10,
    "MEDAE_LOG10": MEDAE_LOG10,

    "MAE_REAL": MAE_REAL,
    "MSE_REAL": MSE_REAL,
    "RMSE_REAL": RMSE_REAL,
    "MAPE_REAL": MAPE_REAL,
    "MEDAE_REAL": MEDAE_REAL,
    "ACC_MODELO": ACC_MODELO}

    mlflow.log_metrics(metricas_mlflow)

2026/03/03 21:30:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:30:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:31:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:31:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:32:03 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:32:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:32:26 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:33:02 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:34:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:34:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:35:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:35:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:35:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:36:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:36:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:36:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:37:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/03/03 21:38:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\Guilh\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run kindly-stag-322 at: http://127.0.0.1:5000/#/experiments/540394382883761644/runs/f8ebe2fe47384330ad5ad5f061e67cf8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/540394382883761644